# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME', 'vendor/bundle']


# Site Settings
title: "FOSS4GNL 2025"
email: "foss4g@osgeo.nl"
description: "FOSS4GNL conference website 2025"
baseurl: ""
url: "https://foss4g.nl"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "OSGeo.nl"
organizerAlternateName: "Open Source Geo Nederland"
organizerDescription: "..."
organizerEmail: "foss4g@osgeo.nl"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://osgeo.nl/"

# Head
metaKeywords: "event, osgeo, conferentie, open source, geo, gis, WUR, geographic, nederland, Wageningen, osgeonl, Wageningen Universiteit, Geodesk"
twitterAccount: "@osgeonl"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
#  - {permalink: "/blog/", text: "Nieuws"}
#  - {permalink: "/workshops/", text: "Workshops"}
#  - {permalink: "/conference/", text: "Programma"}
# - {permalink: "/photos/", text: "Foto's"}
#  - {permalink: "/speakers/", text: "Sprekers"}
bottomNavigationLinks:
#  - {link: "https://www.eventbrite.nl/e/tickets-foss4gnl-2024-671614857117", text: "Aanmelden"}
#  - {link: "https://foss4g.nl", text: "Presentaties"}
rightNavigationButtons:
  #- {link: "https://www.eventbrite.nl/e/tickets-foss4gnl-2024-671614857117", text: "Aanmelden"}
  #- {link: "https://foss4g.nl", text: "Presentaties"}

# About Block
aboutTitle: "Over FOSS4GNL 2025"
aboutBlock:
# - {title: "Conferentie", image: "3dgeoinfo.png", permalink: "/conference/", text: "13/14 September 2024"}

# Statistic Block
statisticBlockImage: "220512_216_Omnia.jpg"
statisticBlock:
 - {count: "8", specialCharacter: "", info: "workshops", detail: ""}
 - {count: "2", specialCharacter: "", info: "keynotes", detail: ""}
 - {count: "45", specialCharacter: "", info: "sessies", detail: ""}
 - {count: "5", specialCharacter: "", info: "parallele tracks", detail: ""}

# Latest News Block
latestNewsTitle: "Nieuws"

# Location Block
locationBlockTitle: "Locatie"
eventLocationName: "Omnia - Wageningen Campus"
eventLocationLink: ""
eventStreetAddress: ""
eventAddressLocality: "Wageningen"
eventAddressLocalityRegion: "Gelderland"
eventPostalCode: ""
eventAddressCountry: "Nederland"
eventStartTime: "2025-07-02T10:00"
eventDoorTime: "09:00"
eventEndTime: "2025-07-03T18:00"
eventPlaceCoordinates: "51.9859156, 5.669655053"
eventPlaceLongitude: 5.669655053
eventPlaceLatitude: 51.9859156
mapCenterCoordinates: "51.9859156, 5.669655053"
mapMobileCenterCoordinates: "51.9859156, 5.669655053"

# Partners Block
partnersTitle: "Sponsors"
becomeSponsorLink: "mailto:foss4g@osgeo.nl"
sponsorsButtonText: "Word een sponsor"


# Organizers Block
organizersTitle: "Organisatie"
becomeSponsorLink: "mailto:foss4g@osgeo.nl"
sponsorsButtonText: "Word een sponsor"


# Tickets Block
ticketsTitle: "Prijslijst"
ticketsInfo: ""
ticketsOffers:
 -
  name: "Conferentiedag 2 juli"
  price: ""
  priceCurrency: "Donatie"
  ticketsNumber: "?"
  buyButtonLink: "https://www.eventbrite.nl/e/tickets-foss4gnl-2019-60886980598"
  buyButtonText: "Koop nu"
  soldOut: false
  soldOutText: "Uitverkocht"
  validFrom: "2019-04-23T00:00"
  validThrough: "2019-06-20T00:00"
 -
  name: "Golden ticket 20 juni"
  price: ""
  priceCurrency: "Donatie"
  ticketsNumber: "?"
  buyButtonLink: "https://www.eventbrite.nl/e/tickets-foss4gnl-2019-60886980598"
  buyButtonText: "Koop nu"
  soldOut: false
  soldOutText: "Uitverkocht"
  validFrom: "2019-04-23T00:00"
  validThrough: "2019-06-20T00:00"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=osgeonl", icon: "twitter"}
footerBlocks:
-
  title: "Contact"
  links:
   - {link: "mailto:foss4g@osgeo.nl", text: "foss4g@osgeo.nl"}

-
  title: "Links"
  links:
    - {link: "https://osgeo.nl/", text: "OSGeo.nl"}
    - {link: "https://wiki.osgeo.org/wiki/Nederlands/", text: "Wiki"}
#    - {permalink: "/cod/", text: "Code of Conduct"
    - {link: "https://www.osgeo.org/code_of_conduct/", text: "Code of Conduct"}

-
  title: "Previous events"
  links:
   - {link: "https://2017.foss4g.nl", text: "FOSS4GNL 2017"}
   - {link: "https://2018.foss4g.nl", text: "FOSS4GNL 2018"}
   - {link: "https://2019.foss4g.nl", text: "FOSS4GNL 2019"}
   - {link: "https://2021.foss4g.nl", text: "FOSS4GNL 2021"}
   - {link: "https://2023.foss4g.nl", text: "FOSS4GNL 2023" }
   - {link: "https://2024.foss4g.nl", text: "FOSS4GNL 2024" }

# Blog
blogTitle: ""
blogCommentsEnabled: false
discusShortName: "osgeo"

# Speakers List Block
showSessions: true
